# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3cc76c6b061b2842aee78e0a03babb43ab45231b2b9b688ac8d754e6549dad55b6ec67c33b49770c9279e6c3c3788d7e98c2b423d09a90797d0171d1e676cf9

test:
  secret_key_base: 7624418e5402c0f99254725b4d0d88bfaca759c72b47ce46a7a0735d37167dac311f6030ee3801554f6ef34de480ca08c5e29b2f0836585c8d042c7969046a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
